### ISSUE TITLE
java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by 123avi** [cakesolutions/scala-kafka-client#105]
Hi , 
Not sure that this a _scala-kafka-client_ issue, but I see a lot Connection refused exception lines in the log. Although everything seems to be working properly - messages are published and consumed as expected. Below is the full log (as an example checkout this [project](https://github.com/123avi/kafka-akka-example/tree/logback) , make sure to use branch name _logback_).
```
TKD [kafka-producer-network-thread | producer-1] DEBUG o.apache.kafka.clients.NetworkClient - Node -1 disconnected.
TKD [kafka-producer-network-thread | producer-1] DEBUG o.apache.kafka.clients.NetworkClient - Give up sending metadata request since no node is available
TKD [kafka-producer-network-thread | producer-2] DEBUG o.apache.kafka.clients.NetworkClient - Initialize connection to node -1 for sending metadata request
TKD [MyActorSystem-akka.actor.default-dispatcher-2] DEBUG o.apache.kafka.clients.NetworkClient - Initialize connection to node -1 for sending metadata request
TKD [MyActorSystem-akka.actor.default-dispatcher-5] DEBUG o.apache.kafka.clients.NetworkClient - Initialize connection to node -1 for sending metadata request
TKD [kafka-producer-network-thread | producer-2] DEBUG o.apache.kafka.clients.NetworkClient - Initiating connection to node -1 at localhost:9092.
TKD [MyActorSystem-akka.actor.default-dispatcher-2] DEBUG o.apache.kafka.clients.NetworkClient - Initiating connection to node -1 at localhost:9092.
TKD [MyActorSystem-akka.actor.default-dispatcher-5] DEBUG o.apache.kafka.clients.NetworkClient - Initiating connection to node -1 at localhost:9092.
TKD [kafka-producer-network-thread | producer-2] DEBUG o.a.kafka.common.network.Selector - Connection with localhost/127.0.0.1 disconnected
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:51)
	at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:73)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:323)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:291)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:260)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:236)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:135)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by 123avi** [comment]
my bad, sorry

**Comment by crapoulou** [comment]
Hello,

Could you please tell us how you fixed it as I get the same issue ?
It's on a local server, (no firewall) and netstat is ok : server is listening !

Thank you.
