### ISSUE TITLE
Exception thrown when kafka consumer actor is polling

### ISSUE THREAD

**Issue by dmartindelorme** [cakesolutions/scala-kafka-client#92]
When I launch my Play application, it instantiates an actor handling a kafka consumer actor this way: 
```
class ConsumerActor @Inject()(configuration: Configuration) extends Actor {

  val logger = Logger(this.getClass)

  def topic: String

  def consumerActorName: String

  val consumerConfig: Config = configuration.underlying.as[Config]("kafka.consumer")

  val consumerActorConfig: Config = configuration.underlying.as[Config]("kafka.actor")

  val consumerConf: Conf[String, String] = KafkaConsumer.Conf(consumerConfig, new StringDeserializer, new StringDeserializer)

  val actorConf: KafkaConsumerActor.Conf = KafkaConsumerActor.Conf().withConf(consumerActorConfig)

  val recordsExt: Extractor[Any, ConsumerRecords[String, String]] = ConsumerRecords.extractor[String, String]

  val consumer: ActorRef = context.actorOf(KafkaConsumerActor.props(consumerConf, actorConf, self), consumerActorName)
  context.watch(consumer)

  override def preStart(): Unit = {
    super.preStart()
    consumer ! Subscribe.AutoPartition(List(topic))
  }

  override def postStop(): Unit = {
    consumer ! Unsubscribe
    super.postStop()
  }

  override def receive: Receive = {
    // Records from Kafka
    case recordsExt(records) =>
      processRecords(records.pairs)
      consumer ! Confirm(records.offsets, commit = true)
  }

  protected def processRecords(records: Seq[(Option[String], String)]): Unit = { ... }
}
``` 

My configuration is as follows:
```
## Kafka
#
kafka {
  bootstrap.servers = "localhost:9092"
  producer {
    bootstrap.servers = ${kafka.bootstrap.servers}
    acks = "all"
    compression.type = "gzip"
    retries = 3
  }
  consumer {
    bootstrap.servers = ${kafka.bootstrap.servers}
    group.id = "test-group"
    auto.offset.reset = "earliest"
    enable.auto.commit = "false"
  }
  actor {
    schedule.interval = 1 second
    unconfirmed.timeout = 3 seconds
    max.redeliveries = 3
  }
}
```

And my Guice module for actors looks like this: 
```
class AkkaModule extends ScalaModule with AkkaGuiceSupport {

  /**
    * Configures the module.
    */
  def configure() {
    // bind consumer
    bindActor[ConsumerActor](ConsumerActor.name)
  }
}
```

I have the following exception when the kafka consumer actor tries to poll the broker for new messages: 
```
cakesolutions.kafka.akka.KafkaConsumerActor$ConsumerException: Exception thrown from Kafka consumer!
	at cakesolutions.kafka.akka.KafkaConsumerActorImpl.cakesolutions$kafka$akka$KafkaConsumerActorImpl$$consumerFailure(KafkaConsumerActor.scala:766)
	at cakesolutions.kafka.akka.KafkaConsumerActorImpl.tryWithConsumer(KafkaConsumerActor.scala:728)
	at cakesolutions.kafka.akka.KafkaConsumerActorImpl.cakesolutions$kafka$akka$KafkaConsumerActorImpl$$pollKafka(KafkaConsumerActor.scala:709)
	at cakesolutions.kafka.akka.KafkaConsumerActorImpl$$anonfun$cakesolutions$kafka$akka$KafkaConsumerActorImpl$$ready$1.applyOrElse(KafkaConsumerActor.scala:507)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
	at cakesolutions.kafka.akka.KafkaConsumerActorImpl.aroundReceive(KafkaConsumerActor.scala:356)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
Caused by: org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'correlation_id': java.nio.BufferUnderflowException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73)
	at org.apache.kafka.common.requests.ResponseHeader.parse(ResponseHeader.java:53)
	at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:376)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:449)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:269)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:180)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:193)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:248)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1013)
```

Do you have any idea where it comes from ?

**Comment by jkpl** [comment]
It could caused be a Kafka server and client mismatch. Which versions of client and server are you running?

**Comment by dmartindelorme** [comment]
I'm using kafka server version 0.10.1.1 and scala-kafka-client version 0.10.1.2. I checked the client dependencies but it seems to be ok [here](https://github.com/cakesolutions/scala-kafka-client/blob/v0.10.1.2/project/Dependencies.scala).

**Comment by dmartindelorme** [comment]
I also tried with kafka server v0.10.0.1 and the client v0.10.0.0 but I have the same error.

**Comment by simonsouter** [comment]
That error surely indicates a client-server mismatch.  I would double check what version of the Kafka Java Driver is actually being used.  The scala-kafka-client does reference one, but maybe you have specified it separately in your build.sbt?  If you are using intellij, check in External Libraries.

This sbt plugin can also be useful: https://github.com/jrudolph/sbt-dependency-graph to see exactly what you are using.

**Comment by dmartindelorme** [comment]
I have checked the external libraries and the version of the dependencies are correct. I have also tested various scenarios, by using the consumer actor, the consumer wrapper or even the java consumer directly and I have the same error every time.

It leads to believe that everything is ok with my code and dependencies and that the version of the kafka server I installed with homebrew is incorrect (even though homebrew claims the version is 0.10.1.1). I will try to run my code with a manually installed kafka server instead and keep you posted.

**Comment by dmartindelorme** [comment]
With a manually installed kafka server I now have the following exception: 
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[SchemaException: Error reading field 'topic_metadata': Error reading array of size 1936028205, only 40 bytes available]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'topic_metadata': Error reading array of size 1936028205, only 40 bytes available
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73)
	at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:380)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:449)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:269)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:180)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:193)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:248)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1013)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:979)
```

**Comment by dmartindelorme** [comment]
I cleaned up all the files used by my previous kafka instances (especially the logs, I made a fresh reinstall with homebrew and that worked for me. Thanks

**Comment by donatelloOo** [comment]
just in case ... as it's an header field ... just check you are targeting a kafka port which is actually running a real kafka server ... this may happen it's a listenning port that has nothing to do with kafka !
